module.exports = {
  PAGE_SIZE: 8,
  OK: 'OK',
  FAIL: 'FAIL',
  SUCCESS: 'SUCCESS',
  ERROR: 'ERROR',
  PAYPAL: 'PAYPAL',
  COD: 'COD',
  VNPAY: 'VNPAY',
  MOMO: 'MOMO',
  ZALOPAY: 'ZALOPAY',
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  DONE: 'DONE',
  CANCELED: 'CANCELED',
  OVERSEA: 'OVERSEA',
  INLAND: 'INLAND',
  MALE: 'MALE',
  FEMALE: 'FEMALE',
  BISEXUAL: 'BISEXUAL',
  SUPER: 0,
  ADMIN: 1,
  USER: 2,
  DEFAULT: 'DEFAULT',
  GOOGLE: 'GOOGLE',
  GHN: 'GHN',
  GHTK: 'GHTK',
  wsConnectionName: {
    NOTIFICATION: 'notification',
  },
  wsCommands: {
    PUSH_MESSAGE: 'PUSH_MESSAGE',
    CREATE_ORDER: 'CREATE_ORDER',
  },
  CLIENT_API: 'https://kltn-client-v1.vercel.app',
};
